// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from "@hotwired/stimulus"
import HelloController from "./hello_controller.ts"

const application = Application.start()
application.register("hello", HelloController)
