FROM ruby:3.4.1-slim

# Install dependencies
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    npm \
    git

# Install yarn
RUN npm install -g yarn

# Set working directory
WORKDIR /app

# Copy Gemfile and install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy the rest of the application
COPY . .

# Install JavaScript dependencies
RUN yarn install

# Precompile assets
RUN bundle exec rake assets:precompile

# Start the application
CMD ["./bin/dev"] 